### ISSUE TITLE
App crash on AB detail page with setting drop items

### ISSUE THREAD

**Issue by item4** [Fate-Grand-Automata/FGA#1049]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

KR

### FGA build number

1597

### Describe the bug

App must crash on auto battle script detail page with settings drop items with landscape viewport.

#### Crash Example
1. Open AB script list
2. Open drop item selected AB
3. Scroll down
4. See crash

https://user-images.githubusercontent.com/559952/147623181-2f9d3acb-5cc8-4678-a9c9-e3dfa281e3f0.mp4

#### No Crash Example
1. Open AB script list
2. Open AB
3. Turn off item selection
4. Scroll down
5. See no crash

https://user-images.githubusercontent.com/559952/147623185-8c3c43fa-7e53-4998-880f-8aec49a432cd.mp4

### Device model

Samsung Galaxy Note20 Ultra

### Android version

11

### Screen size

2316x1080

### RAM

idk

**Comment by reconman** [comment]
Can reproduce, here's a stacktrace:

```
2022-01-04 00:38:47.944 5735-5735/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mathewsachin.fategrandautomata.debug, PID: 5735
    java.lang.IllegalStateException: Asking for intrinsic measurements of SubcomposeLayout layouts is not supported. This includes components that are built on top of SubcomposeLayout, such as lazy lists, BoxWithConstraints, TabRow, etc. To mitigate this:
    - if intrinsic measurements are used to achieve 'match parent' sizing,, consider replacing the parent of the component with a custom layout which controls the order in which children are measured, making intrinsic measurement not needed
    - adding a size modifier to the component, in order to fast return the queried intrinsic measurement.
        at androidx.compose.ui.node.LayoutNode$NoIntrinsicsMeasurePolicy.androidx.compose.ui.node.LayoutNode$NoIntrinsicsMeasurePolicy.minIntrinsicHeight(LayoutNode.kt:2)
                                                                         minIntrinsicHeight
        at androidx.compose.ui.node.InnerPlaceable.androidx.compose.ui.node.IntrinsicsPolicy.minIntrinsicHeight(InnerPlaceable.kt:6)
                                                   minIntrinsicHeight
        at androidx.compose.ui.layout.MeasuringIntrinsics$DefaultIntrinsicMeasurable.measure-BRTryo0(LayoutModifier.kt:8)
        at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(Padding.kt:13)
        at androidx.compose.ui.layout.LayoutModifier$DefaultImpls.androidx.compose.ui.layout.MeasuringIntrinsics.minHeight$ui_release(LayoutModifier.kt:7)
                                                                  minIntrinsicHeight
        at androidx.compose.foundation.layout.PaddingValuesModifier.minIntrinsicHeight(Padding.kt:1)
        at androidx.compose.ui.node.ModifiedLayoutNode.minIntrinsicHeight(ModifiedLayoutNode.kt:4)
        at androidx.compose.ui.layout.MeasuringIntrinsics$DefaultIntrinsicMeasurable.measure-BRTryo0(LayoutModifier.kt:8)
        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
        at androidx.compose.ui.layout.LayoutModifier$DefaultImpls.androidx.compose.ui.layout.MeasuringIntrinsics.minHeight$ui_release(LayoutModifier.kt:7)
                                                                  minIntrinsicHeight
        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.minIntrinsicHeight(GraphicsLayerModifier.kt:1)
        at androidx.compose.ui.node.ModifiedLayoutNode.minIntrinsicHeight(ModifiedLayoutNode.kt:4)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.minIntrinsicHeight(DelegatingLayoutNodeWrapper.kt:2)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.minIntrinsicHeight(DelegatingLayoutNodeWrapper.kt:2)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.minIntrinsicHeight(DelegatingLayoutNodeWrapper.kt:2)
        at androidx.compose.ui.node.LayoutNode.androidx.compose.ui.node.OuterMeasurablePlaceable.minIntrinsicHeight(LayoutNode.kt:3)
                                               minIntrinsicHeight
        at androidx.compose.foundation.layout.IntrinsicMeasureBlocks$VerticalMinHeight$1$1.androidx.compose.foundation.layout.IntrinsicMeasureBlocks$VerticalMinHeight$1$1.invoke(RowColumnImpl.kt:3)
                                                                                           invoke
        at androidx.compose.foundation.layout.RowColumnImplKt.androidx.compose.foundation.layout.RowColumnImplKt.intrinsicMainAxisSize(RowColumnImpl.kt:5)
                                                              androidx.compose.foundation.layout.RowColumnImplKt.intrinsicSize
                                                              access$intrinsicSize
        at androidx.compose.foundation.layout.IntrinsicMeasureBlocks$VerticalMinHeight$1.androidx.compose.foundation.layout.IntrinsicMeasureBlocks$VerticalMinHeight$1.invoke(RowColumnImpl.kt:5)
                                                                                         invoke
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.minIntrinsicHeight(RowColumnImpl.kt:7)
        at androidx.compose.ui.node.InnerPlaceable.androidx.compose.ui.node.IntrinsicsPolicy.minIntrinsicHeight(InnerPlaceable.kt:6)
                                                   minIntrinsicHeight
        at androidx.compose.ui.layout.MeasuringIntrinsics$DefaultIntrinsicMeasurable.measure-BRTryo0(LayoutModifier.kt:8)
        at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(Padding.kt:9)
        at androidx.compose.ui.layout.LayoutModifier$DefaultImpls.androidx.compose.ui.layout.MeasuringIntrinsics.minHeight$ui_release(LayoutModifier.kt:7)
                                                                  minIntrinsicHeight
        at androidx.compose.foundation.layout.PaddingModifier.minIntrinsicHeight(Padding.kt:1)
        at androidx.compose.ui.node.ModifiedLayoutNode.minIntrinsicHeight(ModifiedLayoutNode.kt:4)
        at androidx.compose.foundation.layout.SizeModifier.minIntrinsicHeight(Size.kt:4)
        at androidx.compose.ui.node.ModifiedLayoutNode.minIntrinsicHeight(ModifiedLayoutNode.kt:4)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.minIntrinsicHeight(DelegatingLayoutNodeWrapper.kt:2)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.minIntrinsicHeight(DelegatingLayoutNodeWrapper.kt:2)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.minIntrinsicHeight(DelegatingLayoutNodeWrapper.kt:2)
        at androidx.compose.ui.layout.MeasuringIntrinsics$DefaultIntrinsicMeasurable.measure-BRTryo0(LayoutModifier.kt:8)
        at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:12)
        at androidx.compose.ui.layout.LayoutModifier$DefaultImpls.androidx.compose.ui.layout.MeasuringIntrinsics.minHeight$ui_release(LayoutModifier.kt:7)
                                                                  minIntrinsicHeight
        at androidx.compose.foundation.layout.FillModifier.minIntrinsicHeight(Size.kt:1)
        at androidx.compose.ui.node.ModifiedLayoutNode.minIntrinsicHeight(ModifiedLayoutNode.kt:4)
        at androidx.compose.ui.node.LayoutNode.androidx.compose.ui.node.OuterMeasurablePlaceable.minIntrinsicHeight(LayoutNode.kt:3)
                                               minIntrinsicHeight
        at androidx.compose.ui.layout.DefaultIntrinsicMeasurable.measure-BRTryo0(Layout.kt:8)
        at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:10)
        at androidx.compose.ui.layout.MeasurePolicy$DefaultImpls.minIntrinsicHeight(MeasurePolicy.kt:8)
        at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.minIntrinsicHeight(Box.kt:1)
        at androidx.compose.ui.node.InnerPlaceable.androidx.compose.ui.node.IntrinsicsPolicy.minIntrinsicHeight(InnerPlaceable.kt:6)
                                                   minIntrinsicHeight
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.minIntrinsicHeight(DelegatingLayoutNodeWrapper.kt:2)
        at androidx.compose.ui.node.LayoutNode.androidx.compose.ui.node.OuterMeasurablePlaceable.minIntrinsicHeight(LayoutNode.kt:3)
                                               minIntrinsicHeight
        at androidx.compose.foundation.layout.IntrinsicMeasureBlocks$HorizontalMinHeight$1$1.androidx.compose.foundation.layout.IntrinsicMeasureBlocks$HorizontalMinHeight$1$1.invoke(RowColumnImpl.kt:3)
                                                                                             invoke
        at androidx.compose.foundation.layout.RowColumnImplKt.androidx.compose.foundation.layout.RowColumnImplKt.intrinsicCrossAxisSize(RowColumnImpl.kt:21)
                                                              androidx.compose.foundation.layout.RowColumnImplKt.intrinsicSize
                                                              access$intrinsicSize
        at androidx.compose.foundation.layout.IntrinsicMeasureBlocks$HorizontalMinHeight$1.androidx.compose.foundation.layout.IntrinsicMeasureBlocks$HorizontalMinHeight$1.invoke(RowColumnImpl.kt:6)
                                                                                           invoke
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.minIntrinsicHeight(RowColumnImpl.kt:7)
        at androidx.compose.ui.node.InnerPlaceable.androidx.compose.ui.node.IntrinsicsPolicy.minIntrinsicHeight(InnerPlaceable.kt:6)
                                                   minIntrinsicHeight
        at androidx.compose.foundation.layout.MinIntrinsicHeightModifier.calculateContentConstraints-l58MMJ0(Intrinsic.kt:1)
        at androidx.compose.foundation.layout.IntrinsicSizeModifier$DefaultImpls.measure-3p2s80s(Intrinsic.kt:1)
        at androidx.compose.foundation.layout.MinIntrinsicHeightModifier.measure-3p2s80s(Intrinsic.kt:1)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.invoke(OuterMeasurablePlaceable.kt:3)
                                                                         invoke
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:70)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OuterMeasurablePlaceable.kt:34)
                                                             remeasure-BRTryo0
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:13)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.measure-3p2s80s(RowColumnImpl.kt:19)
        at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:7)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.invoke(OuterMeasurablePlaceable.kt:3)
                                                                         invoke
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:70)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OuterMeasurablePlaceable.kt:34)
                                                             remeasure-BRTryo0
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:13)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
        at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:10)
        at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:7)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
        at androidx.compose.ui.graphics.BlockGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
        at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(Padding.kt:9)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
        at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(Padding.kt:9)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.invoke(OuterMeasurablePlaceable.kt:3)
                                                                         invoke
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:70)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:1)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OuterMeasurablePlaceable.kt:34)
                                                             remeasure-BRTryo0
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:13)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
        at androidx.compose.foundation.lazy.LazyListPrefetcher.onPostMeasure-VKLhPVY(LazyListPrefetcher.android.kt:22)
        at androidx.compose.foundation.lazy.LazyListKt$LazyList$1.androidx.compose.foundation.lazy.LazyListKt$LazyList$1.invoke-0kLqBqw(LazyList.kt:175)
                                                                  invoke
        at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:19)
        at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:7)
        at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(Padding.kt:13)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
```
I have no idea yet on how to solve this.
