### ISSUE TITLE
It says "width must be positive " and it does'nt choose support

### ISSUE THREAD

**Issue by anyangpiggy** [Fate-Grand-Automata/FGA#1321]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [x] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)

### FGO server

KR

### FGA build number

1787

### Describe the bug

It says "width must be positive and don't choose support

last time i run FGA it worked well but now it doen't work

### Video

[Error](https://youtu.be/ZinChG3CrH8) 

### Device model

LG Q92

### Android version

12

### Screen size

2400x1080

### RAM

6

**Comment by anyangpiggy** [comment]
It happened before update too

**Comment by anyangpiggy** [comment]
I don't know what is it but

**Comment by anyangpiggy** [comment]
I don't know what is it for but there is copy button in error page? So i paste it here

null

t4.a$b
	at t4.a.b(AutoBattle.kt:3)
	at t5.e.y(EntryPoint.kt:3)
	at g6.a.run(Unknown Source:2)

**Comment by anyangpiggy** [comment]
It works well in old version(1664)

**Comment by anyangpiggy** [comment]
I redownload old ver and update it and now it works well

**Comment by reconman** [comment]
Problem was probably caused by a corrupted support image.
