### ISSUE TITLE
Touchscreen supported device must report faketouch

### ISSUE THREAD

**Issue by NepPure** [Fate-Grand-Automata/FGA#1719]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

CN

### FGA build number

2288

### Describe the bug

https://github.com/remote-android/redroid-doc/issues/357#issuecomment-1867624565

This should not be a problem with FGA, but rather due to the particularity of Android in docker.

I wonder if FGA can provide some details about this error, I will help improve redroid.

```
null

m5.b
	at m5.p.v(SourceFile:20)
	at androidx.lifecycle.l0.c(SourceFile:831)
	at androidx.lifecycle.l0.invoke(SourceFile:23)
	at t6.a.run(SourceFile:3)

```

### Video

![image](https://github.com/Fate-Grand-Automata/FGA/assets/12379907/361ee34c-b7fe-406f-848f-338cbe0f7569)

### Device model

redroid-13.0.0-latest

### Android version

13

**Comment by vybze** [comment]
It's related to this @ArthurKun21 
https://github.com/Fate-Grand-Automata/FGA/issues/1565

**Comment by NepPure** [comment]
> is this from the play store? could you try manually installing the apk from the github release
> 
> https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary

I downloaded and installed it from GitHub Release. I have tried both installing from files and installing from adb. The same error is reported. It may be caused by some special features of Android for dcoker.

**Comment by NepPure** [comment]
Add logs for `redroid/redroid:13.0.0-latest`.

[tmp.y7UH9Y2FGt.zip](https://github.com/remote-android/redroid-doc/files/13757832/tmp.y7UH9Y2FGt.zip)



```log
--------- beginning of crash
12-23 03:06:43.880    90    90 F libc    : Fatal signal 8 (SIGFPE), code 1 (FPE_INTDIV), fault addr 0x70de49dd27dd in tid 90 (allocator@2.0-s), pid 90 (allocator@2.0-s)
12-23 03:06:43.897   853   853 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-23 03:06:43.897   853   853 F DEBUG   : Build fingerprint: 'redroid/redroid_x86_64/redroid_x86_64:13/TQ3C.230901.001.B1/eng.frank.20231013.070002:userdebug/test-keys'
12-23 03:06:43.897   853   853 F DEBUG   : Revision: '0'
12-23 03:06:43.897   853   853 F DEBUG   : ABI: 'x86_64'
12-23 03:06:43.897   853   853 F DEBUG   : Timestamp: 2023-12-23 03:06:43.887343303+0000
12-23 03:06:43.897   853   853 F DEBUG   : Process uptime: 0s
12-23 03:06:43.897   853   853 F DEBUG   : Cmdline: /vendor/bin/hw/android.hardware.graphics.allocator@2.0-service
12-23 03:06:43.897   853   853 F DEBUG   : pid: 90, tid: 90, name: allocator@2.0-s  >>> /vendor/bin/hw/android.hardware.graphics.allocator@2.0-service <<<
12-23 03:06:43.897   853   853 F DEBUG   : uid: 1000
12-23 03:06:43.897   853   853 F DEBUG   : signal 8 (SIGFPE), code 1 (FPE_INTDIV), fault addr 0x000070de49dd27dd
12-23 03:06:43.897   853   853 F DEBUG   :     rax 0000000000000100  rbx 000070df1a029010  rcx 0000000000000000  rdx 0000000000000000
12-23 03:06:43.897   853   853 F DEBUG   :     r8  000070deea02f6b0  r9  0000000000000001  r10 0000000000000003  r11 0000000000000002
12-23 03:06:43.897   853   853 F DEBUG   :     r12 0000000000000004  r13 0000000000000004  r14 0000000000000035  r15 000070df0a03ab40
12-23 03:06:43.897   853   853 F DEBUG   :     rdi 00007fff1eb3ff74  rsi 0000000000000001
12-23 03:06:43.897   853   853 F DEBUG   :     rbp 000070deea02f6a0  rsp 00007fff1eb3fe80  rip 000070de49dd27dd
12-23 03:06:43.897   853   853 F DEBUG   : backtrace:
12-23 03:06:43.897   853   853 F DEBUG   :       #00 pc 00000000000067dd  /vendor/lib64/hw/gralloc.gbm.so (gralloc_gbm_bo_create+621)
12-23 03:06:43.897   853   853 F DEBUG   :       #01 pc 00000000000061e6  /vendor/lib64/hw/gralloc.gbm.so
12-23 03:06:43.897   853   853 F DEBUG   :       #02 pc 0000000000004354  /vendor/lib64/hw/android.hardware.graphics.allocator@2.0-impl.so (android::hardware::graphics::allocator::V2_0::passthrough::detail::Gralloc0HalImpl<android::hardware::graphics::allocator::V2_0::hal::AllocatorHal>::allocateBuffers(android::hardware::hidl_vec<unsigned int> const&, unsigned int, unsigned int*, std::__1::vector<native_handle const*, std::__1::allocator<native_handle const*> >*)+292) (BuildId: 1a5679ebe4509a1a737939f9d3bc7eb8)
12-23 03:06:43.897   853   853 F DEBUG   :       #03 pc 0000000000004663  /vendor/lib64/hw/android.hardware.graphics.allocator@2.0-impl.so (android::hardware::graphics::allocator::V2_0::hal::detail::AllocatorImpl<android::hardware::graphics::allocator::V2_0::IAllocator, android::hardware::graphics::allocator::V2_0::hal::AllocatorHal>::allocate(android::hardware::hidl_vec<unsigned int> const&, unsigned int, std::__1::function<void (android::hardware::graphics::mapper::V2_0::Error, unsigned int, android::hardware::hidl_vec<android::hardware::hidl_handle> const&)>)+83) (BuildId: 1a5679ebe4509a1a737939f9d3bc7eb8)
12-23 03:06:43.897   853   853 F DEBUG   :       #04 pc 000000000000e463  /apex/com.android.vndk.v33/lib64/android.hardware.graphics.allocator@2.0.so (android::hardware::graphics::allocator::V2_0::BnHwAllocator::_hidl_allocate(android::hidl::base::V1_0::BnHwBase*, android::hardware::Parcel const&, android::hardware::Parcel*, std::__1::function<void (android::hardware::Parcel&)>)+451) (BuildId: 8cc74abbff773b4243f400de9800cb73)
12-23 03:06:43.897   853   853 F DEBUG   :       #05 pc 000000000000e7e5  /apex/com.android.vndk.v33/lib64/android.hardware.graphics.allocator@2.0.so (android::hardware::graphics::allocator::V2_0::BnHwAllocator::onTransact(unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int, std::__1::function<void (android::hardware::Parcel&)>)+325) (BuildId: 8cc74abbff773b4243f400de9800cb73)
12-23 03:06:43.897   853   853 F DEBUG   :       #06 pc 000000000009ab39  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::BHwBinder::transact(unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int, std::__1::function<void (android::hardware::Parcel&)>)+137) (BuildId: 12acd7a8d896b120f2b2ec0e5a00a104)
12-23 03:06:43.897   853   853 F DEBUG   :       #07 pc 00000000000a014a  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::IPCThreadState::executeCommand(int)+3770) (BuildId: 12acd7a8d896b120f2b2ec0e5a00a104)
12-23 03:06:43.897   853   853 F DEBUG   :       #08 pc 000000000009f135  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::IPCThreadState::getAndExecuteCommand()+229) (BuildId: 12acd7a8d896b120f2b2ec0e5a00a104)
12-23 03:06:43.897   853   853 F DEBUG   :       #09 pc 00000000000a072f  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::IPCThreadState::joinThreadPool(bool)+191) (BuildId: 12acd7a8d896b120f2b2ec0e5a00a104)
12-23 03:06:43.897   853   853 F DEBUG   :       #10 pc 0000000000001928  /vendor/bin/hw/android.hardware.graphics.allocator@2.0-service (main+120) (BuildId: f64afa93aade51f6b9a874d0dce6a85f)
12-23 03:06:43.897   853   853 F DEBUG   :       #11 pc 0000000000050cc9  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+89) (BuildId: f090904cc3ac285a6f190f8003c3eb0e)
12-23 03:06:44.041    87   114 F libc    : /buildbot/src/android/ndk-release-r23/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating" failed
12-23 03:06:44.042    87   114 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 114 (HwBinder:87_1), pid 87 (binder:87_2)
12-23 03:06:44.045   883   883 E AndroidRuntime: FATAL EXCEPTION: main
12-23 03:06:44.045   883   883 E AndroidRuntime: PID: 883
12-23 03:06:44.045   883   883 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.attachApplication(android.app.IApplicationThread, long)' on a null object reference
12-23 03:06:44.045   883   883 E AndroidRuntime: 	at android.app.ActivityThread.attach(ActivityThread.java:7612)
12-23 03:06:44.045   883   883 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7911)
12-23 03:06:44.045   883   883 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-23 03:06:44.045   883   883 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-23 03:06:44.045   883   883 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-23 03:06:44.046   883   883 E AndroidRuntime: Error reporting crash
12-23 03:06:44.046   883   883 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
12-23 03:06:44.046   883   883 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
12-23 03:06:44.046   883   883 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
12-23 03:06:44.046   883   883 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
12-23 03:06:44.046   883   883 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
12-23 03:06:44.058   902   902 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-23 03:06:44.058   902   902 F DEBUG   : Build fingerprint: 'redroid/redroid_x86_64/redroid_x86_64:13/TQ3C.230901.001.B1/eng.frank.20231013.070002:userdebug/test-keys'
12-23 03:06:44.058   902   902 F DEBUG   : Revision: '0'
12-23 03:06:44.058   902   902 F DEBUG   : ABI: 'x86'
12-23 03:06:44.058   902   902 F DEBUG   : Timestamp: 2023-12-23 03:06:44.048152016+0000
12-23 03:06:44.058   902   902 F DEBUG   : Process uptime: 0s
12-23 03:06:44.058   902   902 F DEBUG   : Cmdline: /vendor/bin/hw/android.hardware.audio.service
12-23 03:06:44.058   902   902 F DEBUG   : pid: 87, tid: 114, name: HwBinder:87_1  >>> /vendor/bin/hw/android.hardware.audio.service <<<
12-23 03:06:44.058   902   902 F DEBUG   : uid: 1041
12-23 03:06:44.058   902   902 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
12-23 03:06:44.058   902   902 F DEBUG   : Abort message: '/buildbot/src/android/ndk-release-r23/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating" failed'
12-23 03:06:44.058   902   902 F DEBUG   :     eax 00000000  ebx 00000057  ecx 00000072  edx 00000006
12-23 03:06:44.058   902   902 F DEBUG   :     edi e7522e5e  esi e628d800
12-23 03:06:44.058   902   902 F DEBUG   :     ebp e84e8540  esp e628d7a8  eip e84e8549
12-23 03:06:44.058   902   902 F DEBUG   : backtrace:
12-23 03:06:44.058   902   902 F DEBUG   :       #00 pc 00000549  [vdso] (__kernel_vsyscall+9)
12-23 03:06:44.058   902   902 F DEBUG   :       #01 pc 0005d468  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: aa38a999b4afbf524dc294d4b3b61c09)
12-23 03:06:44.058   902   902 F DEBUG   :       #02 pc 000794c1  /apex/com.android.runtime/lib/bionic/libc.so (abort+209) (BuildId: aa38a999b4afbf524dc294d4b3b61c09)
12-23 03:06:44.058   902   902 F DEBUG   :       #03 pc 000799b1  /apex/com.android.runtime/lib/bionic/libc.so (__assert2+49) (BuildId: aa38a999b4afbf524dc294d4b3b61c09)
12-23 03:06:44.058   902   902 F DEBUG   :       #04 pc 000cb554  /vendor/lib/libc++_shared.so (BuildId: dbfa6bc85c9f80f5ee21e5ce5958bd32c820118f)
12-23 03:06:44.058   902   902 F DEBUG   :       #05 pc 000cb688  /vendor/lib/libc++_shared.so (BuildId: dbfa6bc85c9f80f5ee21e5ce5958bd32c820118f)
12-23 03:06:44.058   902   902 F DEBUG   :       #06 pc 000e4a69  /vendor/lib/libc++_shared.so (BuildId: dbfa6bc85c9f80f5ee21e5ce5958bd32c820118f)
12-23 03:06:44.058   902   902 F DEBUG   :       #07 pc 000e499d  /vendor/lib/libc++_shared.so (std::terminate()+45) (BuildId: dbfa6bc85c9f80f5ee21e5ce5958bd32c820118f)
12-23 03:06:44.058   902   902 F DEBUG   :       #08 pc 000ca5e8  /vendor/lib/libc++_shared.so (std::__ndk1::thread::~thread()+40) (BuildId: dbfa6bc85c9f80f5ee21e5ce5958bd32c820118f)
12-23 03:06:44.058   902   902 F DEBUG   :       #09 pc 000067a5  /vendor/lib/hw/audio.primary.redroid.so
12-23 03:06:44.059   902   902 F DEBUG   :       #10 pc 00019442  /vendor/lib/hw/android.hardware.audio@7.0-impl.so (virtual thunk to android::hardware::audio::V7_0::implementation::Device::~Device()+98) (BuildId: f63ae365a5a0d668f3980691428c56ee)
12-23 03:06:44.059   902   902 F DEBUG   :       #11 pc 0000e88f  /apex/com.android.vndk.v33/lib/libutils.so (android::RefBase::decStrong(void const*) const+95) (BuildId: 0a47f53f330bd80fae32c38df6570510)
12-23 03:06:44.059   902   902 F DEBUG   :       #12 pc 0002d724  /vendor/lib/hw/android.hardware.audio@7.0-impl.so (android::hardware::audio::V7_0::implementation::StreamOut::~StreamOut()+500) (BuildId: f63ae365a5a0d668f3980691428c56ee)
12-23 03:06:44.059   902   902 F DEBUG   :       #13 pc 0002d904  /vendor/lib/hw/android.hardware.audio@7.0-impl.so (virtual thunk to android::hardware::audio::V7_0::implementation::StreamOut::~StreamOut()+52) (BuildId: f63ae365a5a0d668f3980691428c56ee)
12-23 03:06:44.059   902   902 F DEBUG   :       #14 pc 0000e88f  /apex/com.android.vndk.v33/lib/libutils.so (android::RefBase::decStrong(void const*) const+95) (BuildId: 0a47f53f330bd80fae32c38df6570510)
12-23 03:06:44.059   902   902 F DEBUG   :       #15 pc 00091644  /apex/com.android.vndk.v33/lib/libhidlbase.so (android::hidl::base::V1_0::BnHwBase::~BnHwBase()+196) (BuildId: ec84e21646112ff70ba0aa160baadd27)
12-23 03:06:44.059   902   902 F DEBUG   :       #16 pc 000b578c  /vendor/lib/android.hardware.audio@7.0.so (android::hardware::audio::V7_0::BnHwStreamOut::~BnHwStreamOut()+204) (BuildId: aebe35f7786069cb88ecd27a1a1f8c50)
12-23 03:06:44.059   902   902 F DEBUG   :       #17 pc 000b5964  /vendor/lib/android.hardware.audio@7.0.so (virtual thunk to android::hardware::audio::V7_0::BnHwStreamOut::~BnHwStreamOut()+52) (BuildId: aebe35f7786069cb88ecd27a1a1f8c50)
12-23 03:06:44.059   902   902 F DEBUG   :       #18 pc 0000e88f  /apex/com.android.vndk.v33/lib/libutils.so (android::RefBase::decStrong(void const*) const+95) (BuildId: 0a47f53f330bd80fae32c38df6570510)
12-23 03:06:44.059   902   902 F DEBUG   :       #19 pc 0009d807  /apex/com.android.vndk.v33/lib/libhidlbase.so (android::hardware::IPCThreadState::processPendingDerefs()+119) (BuildId: ec84e21646112ff70ba0aa160baadd27)
12-23 03:06:44.059   902   902 F DEBUG   :       #20 pc 0009d9c7  /apex/com.android.vndk.v33/lib/libhidlbase.so (android::hardware::IPCThreadState::joinThreadPool(bool)+183) (BuildId: ec84e21646112ff70ba0aa160baadd27)
12-23 03:06:44.059   902   902 F DEBUG   :       #21 pc 000a9a89  /apex/com.android.vndk.v33/lib/libhidlbase.so (android::hardware::PoolThread::threadLoop()+41) (BuildId: ec84e21646112ff70ba0aa160baadd27)
12-23 03:06:44.059   902   902 F DEBUG   :       #22 pc 00012dbb  /apex/com.android.vndk.v33/lib/libutils.so (android::Thread::_threadLoop(void*)+347) (BuildId: 0a47f53f330bd80fae32c38df6570510)
12-23 03:06:44.059   902   902 F DEBUG   :       #23 pc 00012723  /apex/com.android.vndk.v33/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+195) (BuildId: 0a47f53f330bd80fae32c38df6570510)
12-23 03:06:44.059   902   902 F DEBUG   :       #24 pc 000e91c4  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+100) (BuildId: aa38a999b4afbf524dc294d4b3b61c09)
12-23 03:06:44.059   902   902 F DEBUG   :       #25 pc 0007ad07  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+71) (BuildId: aa38a999b4afbf524dc294d4b3b61c09)
12-23 03:06:44.070   143   143 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 143 (main), pid 143 (main)

```

**Comment by reconman** [comment]
I don't think there's anything I can do about it. The docker container doesn't report that it has a touchscreen so the app doesn't work.
