### ISSUE TITLE
FGA crashes and fails to open after update version 2687

### ISSUE THREAD

**Issue by vybze** [Fate-Grand-Automata/FGA#1824]
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA, JP

### FGA build number

2687

### Describe the bug

https://discord.com/channels/1117873862500163684/1243687012267987007

### Video

https://discord.com/channels/1117873862500163684/1243687012267987007

### Device model

Motorola G72

### Android version

13

**Comment by lassknight1** [comment]
same, new update make it crash.

**Comment by Rajvir8** [comment]
I also had this issue, downgrading to 2683 sadly did not fix the issue, but downgrading to 2643 fixes the problem entirely.

Will just have to wait awhile before updating as I'm sure they'll fix it, although it's sad that I've lost all my prior auto's sadly. Should take this as a note and export my auto's more often as a backup.

In my case I'm using LDPlayer.

**Comment by john-bao-git** [comment]
Happening to me as well, just updated it from the Play Store.

Device is Samsung S21, Android 14.

**Comment by Andrew0i** [comment]
Also experiencing it after updating with the latest release. Device is POCO F4, Android 13. 

Here's the debug logs after application crashed:

`java.lang.NoClassDefFoundError: Failed resolution of: Lio/github/fate_grand_automata/prefs/core/PrefsCore;
	at z2.k.get(SourceFile:162)
	at Y1.a.get(SourceFile:14)
	at z2.k.get(SourceFile:135)
	at Y1.a.get(SourceFile:14)
	at i.i.a(SourceFile:50)
	at c.k.onCreate(SourceFile:31)
	at i.j.onCreate(SourceFile:1)
	at io.github.fate_grand_automata.ui.main.MainActivity.t(SourceFile:1)
	at io.github.fate_grand_automata.ui.main.MainActivity.onCreate(SourceFile:1)
	at android.app.Activity.performCreate(Activity.java:8458)
	at android.app.Activity.performCreate(Activity.java:8427)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1385)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: io.github.fate_grand_automata.prefs.core.PrefsCore
	... 25 more
`
