### ISSUE TITLE
Running into OpenCV exception error when selecting support

### ISSUE THREAD

**Issue by edgykuma** [Fate-Grand-Automata/FGA#676]
Before opening an issue:
- [O] I tested the latest release
- [O] I looked at other issues (even the closed ones)
- [O] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [O] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Include steps to reproduce the error if required

When the tool searches for a support, it runs into an OpenCV exception. Seems like there is a problem with the images loading. I've tried creating a new folder and copying the support images, but the problem persists. 

Dump of error message:
```
Unexpected Error: cv::Exception: OpenCV(4.4.0) /build/master_pack-android/opencv/modules/imgcodecs/src/loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'


0 refills used out of 3
Time: 00:04

java.lang.Exception: Unexpected Error: cv::Exception: OpenCV(4.4.0) /build/master_pack-android/opencv/modules/imgcodecs/src/loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'


0 refills used out of 3
Time: 00:04
	at h.a.a.c.a.a.z(AutoBattle.kt:32)
	at h.a.b.b.c(EntryPoint.kt:3)
	at g0.n.a.run(Thread.kt:1)
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.4.0) /build/master_pack-android/opencv/modules/imgcodecs/src/loadsave.cpp:753: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'
]
	at org.opencv.imgcodecs.Imgcodecs.imdecode_0(Native Method)
	at h.a.a.j.a.<init>(DroidCvPattern.kt:7)
	at h.a.a.l.n.g(ImageLoader.kt:9)
	at h.a.a.l.n.b(ImageLoader.kt:4)
	at h.a.a.c.g.g(ImageLocator.kt:1)
	at h.a.a.c.k.k.B(Support.kt:5)
	at a0.c(kotlin-style lambda group:16)
	at h.a.a.c.k.s.c(Support.kt:5)
	at h.a.b.y.a.t(AutomataApi.kt:5)
	at h.a.a.c.b.t(Unknown Source:7)
	at h.a.a.c.k.k.t(Unknown Source:7)
	at h.a.a.c.k.k.G(Support.kt:1)
	at h.a.a.c.k.k.H(Support.kt:27)
	at h.a.a.c.a.a$a.c(kotlin-style lambda group:396)
	at h.a.a.c.a.a.B(AutoBattle.kt:29)
	at h.a.a.c.a.a.z(AutoBattle.kt:31)
	... 2 more
```

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

*FGA settings*

https://user-images.githubusercontent.com/17093248/106309972-b5df1d00-6217-11eb-8a2b-041e3014e2b5.mp4

Note that I am unable to screen record and run the service at the same time (the recording just stops). If you know of a way I can do this please let me know and I'll be happy to follow up. 

**Device Info (please fill at-least 'Device model'):**
 - Device model: Samsung Galaxy Z Fold 2
 - Screen size: 590 x 736
 - Android Version: Android 10
 - RAM: [e.g. 3GB]

**Comment by edgykuma** [comment]
Figured it out. The error results when your FGA support image folders contain a `NOMEDIA` file (reference on what these are [here](https://www.lifewire.com/nomedia-file-4172882)). Removing said file from the folders and subfolders will fix it.

Closing the issue.

**Comment by reconman** [comment]
You can put the .NOMEDIA file into the parent folder of `support` and it will work.
